# Generated by Django 4.2.30 on 2026-06-12 00:08

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('employee', '员工'), ('supervisor', '主管')], default='employee', max_length=20)),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50, unique=True, verbose_name='资产编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('available', '可借用'), ('borrowed', '已借用'), ('pending_maintenance', '待维护'), ('exception_pending', '异常待核'), ('maintaining', '维护中'), ('recovered', '恢复可用'), ('decommissioned', '停用')], default='available', max_length=20, verbose_name='状态')),
                ('specification', models.TextField(blank=True, verbose_name='规格参数')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('last_maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='最后维护日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备类型名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('warning_threshold', models.IntegerField(default=5, verbose_name='库存预警阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='存放位置')),
                ('description', models.TextField(blank=True, verbose_name='位置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField(auto_now_add=True, verbose_name='维护时间')),
                ('maintenance_type', models.CharField(max_length=50, verbose_name='维护类型')),
                ('description', models.TextField(verbose_name='维护说明')),
                ('result', models.TextField(verbose_name='维护结果')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='api.device', verbose_name='设备')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('damage', '损坏'), ('loss', '丢失'), ('overdue', '逾期未还'), ('missing_maintenance', '维护缺失'), ('other', '其他')], max_length=30, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('review_status', models.CharField(choices=[('pending', '待复核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='复核状态')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_result', models.TextField(blank=True, verbose_name='复核结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_records', to='api.device', verbose_name='设备')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.devicetype', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.location', verbose_name='存放位置'),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借用时间')),
                ('expected_return_date', models.DateField(verbose_name='预计归还日期')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('borrow_purpose', models.TextField(verbose_name='借用用途')),
                ('return_notes', models.TextField(blank=True, verbose_name='归还说明')),
                ('damage_notes', models.TextField(blank=True, verbose_name='损坏说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='api.device', verbose_name='设备')),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
    ]
