# Generated by Django 4.2.30 on 2026-06-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_borrow_date', models.DateField(verbose_name='预计借用日期')),
                ('expected_return_date', models.DateField(verbose_name='预计归还日期')),
                ('purpose', models.TextField(verbose_name='预约用途')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('notified', '已通知'), ('fulfilled', '已借出'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='借出时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.device', verbose_name='设备')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
